using System.Text.Json.Nodes;

namespace Incursa.OpenAI.Agents;

/// <summary>
/// Represents the outcome of an agent tool execution.
/// </summary>

public sealed record AgentToolResult
{
    /// <summary>Creates an empty tool result.</summary>
    public AgentToolResult()
        : this(null, null, null)
    {
    }

    /// <summary>Creates a text-only tool result.</summary>
    public AgentToolResult(string? text)
        : this(text, null, null)
    {
    }

    /// <summary>Creates a tool result with text and structured output.</summary>
    public AgentToolResult(string? text, JsonNode? structuredValue)
        : this(text, structuredValue, null)
    {
    }

    /// <summary>Creates a tool result with text, structured output and emitted run items.</summary>
    public AgentToolResult(string? text, JsonNode? structuredValue, IReadOnlyList<AgentRunItem>? items)
    {
        Text = text;
        StructuredValue = structuredValue;
        Items = items;
    }

    /// <summary>Gets or sets plain-text output from tool execution.</summary>
    public string? Text { get; init; }

    /// <summary>Gets or sets structured output payload from tool execution.</summary>
    public JsonNode? StructuredValue { get; init; }

    /// <summary>Gets or sets optional run items generated by the tool.</summary>
    public IReadOnlyList<AgentRunItem>? Items { get; init; }

    /// <summary>Builds a text-only tool result.</summary>
    public static AgentToolResult FromText(string text) => new(text, null, null);

    /// <summary>Builds a text result with emitted run items.</summary>
    public static AgentToolResult FromText(string text, IReadOnlyList<AgentRunItem>? items) => new(text, null, items);

    /// <summary>Builds a structured-result response.</summary>
    public static AgentToolResult FromStructured(JsonNode value) => new(null, value, null);

    /// <summary>Builds a structured-result response with emitted run items.</summary>
    public static AgentToolResult FromStructured(JsonNode value, IReadOnlyList<AgentRunItem>? items) => new(null, value, items);
}
